import { loadMission, createReview, getStatus, getReview, saveHumanReview, exportMarkdown } from './services/reviewService'
import type { HumanReviewRequest, MissionPackage } from './types/contracts'
import { readJson, bad } from './utils/http'
export async function missionLoadHandler(request:Request){try{const body=await readJson(request);const result=loadMission(body?.package as MissionPackage|undefined);return Response.json(result,{status:result.ok?200:422})}catch(e){return bad(e instanceof Error?e.message:'Invalid request')}}
export async function reviewRunHandler(request:Request){try{const body=await readJson(request);const job=createReview(body?.package as MissionPackage|undefined,body?.previous_review_id??null);return Response.json({review_id:job.id,job_id:job.id,status:job.stage,processing_mode:'DETERMINISTIC'},{status:job.stage==='FAILED'?422:202})}catch(e){return bad(e instanceof Error?e.message:'Invalid request')}}
export function statusHandler(id:string){const job=getStatus(id);return job?Response.json({review_id:id,status:job.stage,error:job.error??null,report:job.report?{review_id:job.report.review_id,mission_id:job.report.mission_id,processing_mode:job.report.processing_mode,processing_time_ms:job.report.processing_time_ms}:null}):bad('Review not found.',404)}
export function reviewHandler(id:string){const report=getReview(id);return report?Response.json(report):bad('Review not found.',404)}
export async function humanReviewHandler(request:Request,id:string,fid:string){try{const body=await readJson(request) as HumanReviewRequest;if(!['PENDING','ACKNOWLEDGED','NEEDS_ACTION','DISMISSED_WITH_NOTE'].includes(body.disposition))return bad('Invalid disposition.');if(typeof body.note!=='string'||body.note.length>2000)return bad('Invalid note.');const saved=saveHumanReview(id,fid,body);if(saved===null)return bad('Review not found.',404);if(saved===undefined)return bad('Finding not found.',404);return Response.json(saved)}catch(e){return bad(e instanceof Error?e.message:'Unable to save review action')}}
export function exportHandler(id:string){const md=exportMarkdown(id);if(md===null)return bad('Review not found.',404);return new Response(md,{status:200,headers:{'Content-Type':'text/markdown; charset=utf-8','Content-Disposition':`attachment; filename="LaunchReady-${id}.md"`}})}
