export type Evaluation = 'CHECK_PASSED' | 'REVIEW_REQUIRED' | 'MISSING_EVIDENCE'
export type Diff = 'NEW' | 'RESOLVED' | 'CHANGED' | 'UNRESOLVED'
export type Disposition = 'PENDING' | 'ACKNOWLEDGED' | 'NEEDS_ACTION' | 'DISMISSED_WITH_NOTE'
export interface ReviewNote { state: Disposition; note: string; savedAt: string }
export type ReviewNotes = Record<string, ReviewNote>
export interface Source { id: string; title: string; section: string; excerpt: string }
export interface Finding {
  id: string; title: string; subsystem: string; status: Diff; evaluation: Evaluation
  priority: 'HIGH' | 'MEDIUM' | 'LOW'; previous: number | null; current: number | null
  unit: string; limit: number | null; requirement: string; dataId: string | null
  trend: 'IMPROVING' | 'WORSENING' | 'STABLE' | 'INSUFFICIENT_DATA'
  confidence: 'HIGH' | 'MEDIUM' | 'LOW'; confidenceReasons: string[]
  series: { time: string; value: number }[]; source: Source | null
  impact: string; action: string; gap: boolean
}
export const mission = {
  id: 'ASTER-2-R2', name: 'Aster-2', review: 'Review #02', baseline: 'Review #01',
  timestamp: '2026-10-02T14:30:00Z',
  files: ['mission-parameters.json', 'review-01-baseline.csv', 'demo-requirements.md', 'demo-test-procedures.md'],
}
const series = (values: number[]) => values.map((value, index) => ({ time: `14:${String(index * 5).padStart(2, '0')}`, value }))
const source = (id: string, section: string, excerpt: string): Source => ({ id, title: 'Demo mission requirements', section, excerpt })
export const findings: Finding[] = [
  { id: 'BATTERY-THERMAL', title: 'Battery temperature crossed its limit', subsystem: 'AVIONICS', status: 'NEW', evaluation: 'REVIEW_REQUIRED', priority: 'HIGH', previous: 41, current: 47, unit: '°C', limit: 45, requirement: 'REQ-AV-01 · Battery temperature must be ≤ 45°C.', dataId: 'BAT-TEMP-04', trend: 'WORSENING', confidence: 'HIGH', confidenceReasons: ['Configured requirement is traceable.', 'Seven valid simulated samples cover 30 minutes.', 'Required supporting passage is linked.'], series: series([41, 42, 43, 44, 45, 46, 47]), source: source('DOC-AV-THERMAL', '§4.2.1', 'Illustrative requirement: battery temperature must not exceed 45°C during this demo test. If exceeded, repeat the thermal test under the documented setup and request engineering review.'), impact: 'Temperature increased by 6°C and is now 2°C above the illustrative limit. This is a new violation since the baseline.', action: 'Repeat the battery thermal test and request engineering review under Demo Procedure TH-01.', gap: false },
  { id: 'MOTOR-VIBRATION', title: 'Motor vibration increased within range', subsystem: 'PROPULSION', status: 'CHANGED', evaluation: 'CHECK_PASSED', priority: 'LOW', previous: 3.2, current: 3.8, unit: 'mm/s', limit: 4, requirement: 'REQ-PR-01 · Demo motor vibration must be ≤ 4.0 mm/s.', dataId: 'VIB-07', trend: 'STABLE', confidence: 'MEDIUM', confidenceReasons: ['Valid simulated readings remain within range.', 'Optional contextual test note is unavailable.'], series: series([3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8]), source: source('DOC-PR-VIB', '§2.3', 'Illustrative requirement: vibration must remain at or below 4.0 mm/s. Compare repeat observations using the same test configuration.'), impact: 'The latest value passes this configured check. Raw vibration is rising, but all samples remain within range; the distance-to-range trend is stable.', action: 'Continue comparable observations and obtain the optional test-context note.', gap: false },
  { id: 'CHUTE-DEPLOY-TIME', title: 'Recovery deployment timing resolved', subsystem: 'RECOVERY', status: 'RESOLVED', evaluation: 'CHECK_PASSED', priority: 'LOW', previous: 2.8, current: 2.1, unit: 's', limit: 2.5, requirement: 'REQ-RE-01 · Demo deployment time must be ≤ 2.5 s.', dataId: 'DEPLOY-09', trend: 'IMPROVING', confidence: 'HIGH', confidenceReasons: ['Configured requirement and simulated retest are linked.', 'Current observation is fresh in the demo package.', 'Required test evidence is present.'], series: series([2.8, 2.7, 2.6, 2.5, 2.4, 2.2, 2.1]), source: source('DOC-RE-DEPLOY', '§3.1', 'Illustrative requirement: deployment time must not exceed 2.5 seconds. A resolved timing finding requires a current test record linked to the checklist.'), impact: 'Deployment time fell by 0.7 s and the current test passes its configured check. The previous timing issue is resolved.', action: 'Review the linked retest and acknowledge the resolved finding.', gap: false },
  { id: 'INTERSTAGE-BOND', title: 'Bond inspection evidence is missing', subsystem: 'STRUCTURE', status: 'NEW', evaluation: 'MISSING_EVIDENCE', priority: 'MEDIUM', previous: null, current: null, unit: '', limit: null, requirement: 'REQ-ST-02 · Attach the current bond inspection record.', dataId: null, trend: 'INSUFFICIENT_DATA', confidence: 'LOW', confidenceReasons: ['Required inspection evidence is absent.', 'No numeric observation is available; no trend can be calculated.'], series: [], source: source('DOC-ST-BOND', '§5.2', 'Illustrative requirement: a current interstage bond inspection record must be attached before this review item can be evaluated.'), impact: 'The configured inspection requirement cannot be evaluated. Missing measurements are not replaced with zero.', action: 'Attach the current bond inspection record and rerun the review.', gap: true },
  { id: 'SURFACE-WIND', title: 'Wind improved but remains above limit', subsystem: 'ENVIRONMENT', status: 'CHANGED', evaluation: 'REVIEW_REQUIRED', priority: 'HIGH', previous: 11, current: 9, unit: 'm/s', limit: 8, requirement: 'REQ-EN-01 · Demo surface wind must be ≤ 8 m/s.', dataId: 'WIND-06', trend: 'IMPROVING', confidence: 'HIGH', confidenceReasons: ['Seven comparable simulated observations are present.', 'The illustrative limit and supporting passage are linked.'], series: series([11, 10.8, 10.5, 10, 9.8, 9.3, 9]), source: source('DOC-EN-WIND', '§6.1', 'Illustrative requirement: surface wind must not exceed 8 m/s in this demo scenario. Improving observations do not remove a current exceedance; recheck conditions at the next observation cycle.'), impact: 'Wind fell by 2 m/s, but the latest reading still exceeds the illustrative limit by 1 m/s. Improvement does not resolve this finding.', action: 'Recheck conditions at the next observation cycle; retain the open finding until evidence meets the configured check.', gap: false },
  { id: 'SENSOR-DROPOUT', title: 'Temperature sensor dropout needs review', subsystem: 'AVIONICS', status: 'NEW', evaluation: 'REVIEW_REQUIRED', priority: 'MEDIUM', previous: 0, current: 1, unit: 'events', limit: 0, requirement: 'REQ-AV-03 · Record zero dropout events in the demo sensor test.', dataId: 'SENSOR-17', trend: 'INSUFFICIENT_DATA', confidence: 'HIGH', confidenceReasons: ['A discrete dropout event is explicitly recorded.', 'The configured event check and passage are linked.', 'A time-series trend is unavailable for this event.'], series: [], source: source('DOC-AV-SENSOR', '§4.3', 'Illustrative requirement: log every sensor dropout and flag any event for inspection. Confirm the sensor record before interpreting affected readings.'), impact: 'One dropout event was recorded. This event requires investigation; it does not by itself establish the cause of the battery temperature rise.', action: 'Inspect the sensor record and request a comparable repeat observation.', gap: false },
  { id: 'FIN-INSPECTION', title: 'Fin attachment inspection remains open', subsystem: 'STRUCTURE', status: 'UNRESOLVED', evaluation: 'MISSING_EVIDENCE', priority: 'MEDIUM', previous: null, current: null, unit: '', limit: null, requirement: 'REQ-ST-03 · Attach the completed fin inspection record.', dataId: null, trend: 'INSUFFICIENT_DATA', confidence: 'LOW', confidenceReasons: ['Required completion record is absent.', 'The same gap was present in the previous review.'], series: [], source: null, impact: 'This evidence gap was open previously and remains open. The supporting procedure passage is also unavailable.', action: 'Request the fin inspection record and the applicable procedure from the reviewer.', gap: true },
]
export const subsystems = ['PROPULSION', 'AVIONICS', 'STRUCTURE', 'RECOVERY', 'ENVIRONMENT']
export const valueLabel = (v: number | null, unit: string) => v === null ? 'Not available' : `${v}${unit ? ` ${unit}` : ''}`
export const statusLabel = (s: string) => s.replaceAll('_', ' ')
export function summarize(items = findings, notes: ReviewNotes = {}) {
  return { total: items.length, passed: items.filter(f => f.evaluation === 'CHECK_PASSED').length, review: items.filter(f => f.evaluation === 'REVIEW_REQUIRED').length, gaps: items.filter(f => f.gap).length, reviewed: items.filter(f => notes[f.id]?.state && notes[f.id].state !== 'PENDING').length }
}
export function demoAnswer(question: string, selectedId?: string): { answer: string; citations: string[] } {
  const q = question.toLowerCase()
  const f = findings.find(f => f.id === selectedId) ?? findings.find(f => q.includes(f.id.toLowerCase()) || q.includes(f.id.split('-')[0].toLowerCase()))
  if (/launch|safe|go\/no|approve|clearance/.test(q)) return { answer: 'This review does not approve or certify a launch. It shows configured check results and evidence for human engineering review.', citations: [] }
  if (/missing|gap/.test(q)) return { answer: 'Two required evidence records are missing: the bond inspection and fin attachment inspection. Attach current records before these checks can be evaluated.', citations: ['INTERSTAGE-BOND', 'FIN-INSPECTION'] }
  if (f && /\b(action|next|do|recommend)\b/.test(q)) return { answer: f.action, citations: [f.id] }
  if (f && /source|document|evidence|support/.test(q)) return { answer: f.source ? `${f.requirement}\n\n${f.source.title} ${f.source.section}: “${f.source.excerpt}”` : 'No supporting document passage is linked. Request the applicable procedure; the demo cannot provide one.', citations: [f.id] }
  if (f) return { answer: `${f.impact}\n\nNext step: ${f.action}`, citations: [f.id] }
  if (/wind|improv/.test(q)) return { answer: 'Wind improved from 11 to 9 m/s but is still above the illustrative 8 m/s limit. Battery temperature worsened to 47°C, and two required inspection records remain missing. Improving one signal does not resolve other open findings.', citations: ['SURFACE-WIND', 'BATTERY-THERMAL', 'INTERSTAGE-BOND', 'FIN-INSPECTION'] }
  if (/summary|summar|overview|changed|attention|review/.test(q)) return { answer: 'This simulated review contains seven findings: two configured checks passed, three require review, and two have missing evidence. Focus on battery temperature and wind exceedances, inspect the sensor dropout, and request the two inspection records.', citations: ['BATTERY-THERMAL', 'SURFACE-WIND', 'SENSOR-DROPOUT', 'INTERSTAGE-BOND', 'FIN-INSPECTION'] }
  return { answer: 'The demo assistant supports review summaries, finding explanations, evidence questions, and next steps. Select a finding or try a suggested question. Open-ended answers require your connected AI backend.', citations: [] }
}
export function markdownReport(notes: ReviewNotes): string {
  const s = summarize(findings, notes)
  return [`# LaunchReady AI mission review`, `\nSimulated mission ${mission.name} · ${mission.review} vs ${mission.baseline}`, `Scenario time: ${mission.timestamp}`, `\n${s.total} findings · ${s.passed} checks passed · ${s.review} require review · ${s.gaps} evidence gaps`, '\nAll requirements, measurements, and passages below are illustrative demo data.', ...findings.map(f => `\n## ${f.id}\n${statusLabel(f.evaluation)} · ${f.status} · ${f.priority} priority\n\n${f.requirement}\nPrevious: ${valueLabel(f.previous, f.unit)}; current: ${valueLabel(f.current, f.unit)}\nTrend: ${statusLabel(f.trend)}\nEvidence confidence: ${f.confidence} — ${f.confidenceReasons.join(' ')}\n\n${f.impact}\nNext step: ${f.action}\nSource: ${f.source ? `${f.source.title} ${f.source.section} (${f.source.id})\n> ${f.source.excerpt}` : 'Supporting passage missing'}\nHuman disposition: ${notes[f.id]?.state ?? 'PENDING'}\nReviewer note: ${notes[f.id]?.note ?? 'No note'}\nSaved at: ${notes[f.id]?.savedAt ?? 'Not reviewed'}`), '\nHuman engineering review required. This tool does not approve or certify launches.'].join('\n')
}
