import crypto from 'node:crypto'
import type { MissionPackage, ReviewReport, BackendFinding, ReviewJob, HumanReviewRequest, Disposition } from '../types/contracts'
import { validateBundle } from '../engine/validationEngine'
import { evaluateRules } from '../engine/rulesEngine'
import { applyTrends } from '../engine/trendEngine'
import { calculateDiff } from '../engine/diffEngine'
import { applyConfidence } from '../engine/confidenceEngine'
import { retrieveEvidence } from '../engine/evidenceEngine'
import { validateReport } from '../engine/outputValidator'
import { aster2Package, baselineFindingSnapshot } from '../fixtures/aster2'
import { reviewStore } from '../storage/store'

export const STAGES=['Validate','Normalize','Evaluate Rules','Analyze Trends','Compare Reviews','Retrieve Evidence','Assemble and Validate Report','Save'] as const
const fingerprint=(pkg:MissionPackage)=>crypto.createHash('sha256').update(JSON.stringify(pkg)).digest('hex')
export function loadMission(pkg?:MissionPackage){const p=pkg??aster2Package;const validation=validateBundle(p);if(!validation.valid) return {ok:false,validation};reviewStore.missions.set(p.mission_id,p);return {ok:true,mission:p,validation}}
function makeReport(id:string,pkg:MissionPackage,findings:BackendFinding[],started:number,previousId:string|null):ReviewReport{const now=new Date().toISOString();return {review_id:id,mission_id:pkg.mission_id,input_fingerprint:fingerprint(pkg),rule_engine_version:'1.0.0',processing_time_ms:Date.now()-started,processing_mode:'DETERMINISTIC',status:'COMPLETE',stages:[...STAGES],findings,summary:{total:findings.length,passed:findings.filter(f=>f.status==='CHECK_PASSED').length,review_required:findings.filter(f=>f.status==='REVIEW_REQUIRED').length,missing_evidence:findings.filter(f=>f.status==='MISSING_EVIDENCE').length,evidence_gaps:findings.filter(f=>f.evidence_flags.length>0).length},previous_review_id:previousId,created_at:now,updated_at:now,disclaimer:'Human engineering review required. This tool does not approve or certify launches.',human_review:{}}
}
export function createReview(pkg?:MissionPackage, previousId?:string|null){const p=pkg??aster2Package;const id=`REV-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`;const job:ReviewJob={id,report:null,stage:'Validate',started_at:new Date().toISOString(),updated_at:new Date().toISOString()};reviewStore.jobs.set(id,job); const started=Date.now(); try{const v=validateBundle(p);if(!v.valid) throw new Error(v.errors.join(' ')); job.stage='Normalize'; let fs=evaluateRules(p);job.stage='Analyze Trends';fs=applyTrends(fs,p);job.stage='Compare Reviews';fs=calculateDiff(fs,baselineFindingSnapshot() as any) as BackendFinding[];job.stage='Retrieve Evidence';fs=retrieveEvidence(fs,p);fs=applyConfidence(fs,p);job.stage='Assemble and Validate Report';const report=makeReport(id,p,fs,started,previousId??p.previous_review_id??null);const outputCheck=validateReport(report,p); if(!outputCheck.valid) throw new Error(`Report validation failed: ${outputCheck.errors.join(' ')}`); job.stage='Save';job.report=report;job.stage='COMPLETE';job.updated_at=new Date().toISOString();reviewStore.reports.set(id,report);reviewStore.missions.set(p.mission_id,p);return job}catch(e){job.stage='FAILED';job.error=e instanceof Error?e.message:'Review failed';job.updated_at=new Date().toISOString();return job}}
export function getReview(id:string){return reviewStore.reports.get(id)??null}
export function getStatus(id:string){return reviewStore.jobs.get(id)??null}
export function saveHumanReview(id:string,fid:string,input:HumanReviewRequest){const report=reviewStore.reports.get(id);if(!report)return null;if(!report.findings.some(f=>f.finding_id===fid))return undefined;if(input.disposition==='DISMISSED_WITH_NOTE'&&!input.note.trim())throw new Error('Dismissal requires a note.');report.human_review[fid]={disposition:input.disposition,note:input.note.trim(),timestamp:new Date().toISOString()};report.updated_at=new Date().toISOString();reviewStore.reports.set(id,report);return report.human_review[fid]}
export function exportMarkdown(id:string){const r=getReview(id);if(!r)return null;const lines=[`# LaunchReady AI — ${r.mission_id}`,`Review: ${r.review_id}`,`Mode: ${r.processing_mode}`,``,`## Summary`,`Total: ${r.summary.total}`,`Passed: ${r.summary.passed}`,`Review required: ${r.summary.review_required}`,`Evidence gaps: ${r.summary.evidence_gaps}`,``];for(const f of r.findings){lines.push(`## ${f.title} (${f.finding_id})`,`- Evaluation: ${f.status}`,`- Diff: ${f.diff_category}`,`- Priority: ${f.priority}`,`- Trend: ${f.trend.label}`,`- Evidence confidence: ${f.evidence_confidence.level}`,`- Requirement: ${f.requirement_id}`,`- Data IDs: ${f.data_ids.join(', ')||'None'}`,`- Document chunks: ${f.document_chunk_ids.join(', ')||'None'}`,`- Impact: ${f.impact}`,`- Next step: ${f.recommended_next_step.category} — ${f.recommended_next_step.target}`,`- Human disposition: ${r.human_review[f.finding_id]?.disposition??'PENDING'}`,`- Human note: ${r.human_review[f.finding_id]?.note??''}`,``)}lines.push('Human engineering review required. This tool does not approve or certify launches.');return lines.join('\n')}
